PARENT_EXCLUDE = [
    'Advent',
    'Gear',
]

THEME_EXCLUDE = [
    'Video Games and Accessories',
    'Tabletop Games and Puzzles',
    'Role Play Toys and Costumes',
    'Books',
]

MINIFIGURE_THEMES = [
    'Series 1 Minifigures',
    'Series 2 Minifigures',
    'Series 3 Minifigures',
    'Series 4 Minifigures',
    'Series 5 Minifigures',
    'Series 6 Minifigures',
    'Series 7 Minifigures',
    'Series 8 Minifigures',
    'Series 9 Minifigures',
    'Series 10 Minifigures',
    'Series 11 Minifigures',
    'Series 12 Minifigures',
    'Series 13 Minifigures',
    'Series 14 Minifigures',
    'Series 15 Minifigures',
    'Series 16 Minifigures',
    'Series 17 Minifigures',
    'Series 18 Minifigures',
    'Series 19 Minifigures',
    'Series 20 Minifigures',
    'Series 21 Minifigures',
    'Series 22 Minifigures',
    'Series 23 Minifigures',
    'Collectible Minifigures',
]

BRAND_MINIFIGURE_THEMES = [
    'The Simpsons Series 1',
    'The Simpsons Series 2',
    'Disney Series 1',
    'Disney Series 2',
    'The LEGO Batman Movie Series 1',
    'The LEGO Batman Movie Series 2',
    'DFB Minifigures',
    'Harry Potter and Fantastic Beasts Series 1',
    'Harry Potter and Fantastic Beasts Series 2',
    'The LEGO Batman Movie Series 1',
    'The LEGO Batman Movie Series 2',
]

BRAND_THEMES = [
    'Star Wars',
    'Batman',
    'The LEGO Batman Movie',
    'Justice League',
    'Super Heroes DC',
    'DC Comics Super Heroes',
    'DC Comics',
    'DC Super Hero Girls',
    'DC Super Heroes',
    'The Muppets',
    'Super Heroes Marvel',
    'Marvel Super Heroes',
    'Marvel',
    'X-Men',
    'The Hobbit',
    'The Hobbit and Lord of the Rings',
    'Disney',
    'Harry Potter',
    'The Lord of the Rings',
    'Stranger Things',
    'Angry Birds',
    'Ghostbusters',
    'Fantastic Beasts',
    'Dora the Explorer',
    'The Powerpuff Girls',
    'Scooby-Doo',
    'Guardians of the Galaxy',
    'Spider-Man',
    'Spiderman',
    'Disney Planes',
    'Disney Princess',
    "Disney's Mickey Mouse",
    'Toy Story',
    'Jurassic World: Fallen Kingdom',
    'Jurassic Park III',
    'Jurassic World',
    'McDonalds',
    'Indiana Jones',
    'Prince of Persia',
    'Minecraft',
    'Superman',
    'Avengers',
    'Winnie the Pooh',
    'Pirates of the Caribbean',
    'Iron Man',
    'Ferrari',
    'The Lone Ranger',
    'Teenage Mutant Ninja Turtles',
    'Super Mario',
    'Minions',
    'Frozen',
    'Trolls: World Tour',
    'Scooby-Doo',
    # 'Samsonite',  # NOT a brand. They were managed by them
    'Bob the Builder',
    'Thomas & Friends',
    'SpongeBob SquarePants',
    'Avatar: The Last Airbender',
    'Jake and the Never Land Pirates',
    'Doc McStuffins',
    'Miles From Tomorrowland',
    'Avatar',
    'Overwatch',
    'The Muppets',
    'Williams F1',
    'Looney Tunes',
    'Ben 10',
    'Mixels',
    'Cars',
    'Sofia the First',
]

LEGO_BRAND_THEMES = [
    'Bionicle',
    'The LEGO Movie',
    'The LEGO Movie II',
    'Ninjago',
    'Legends of Chima',
    'Monkie Kid',
    'Dimensions',
    'Nexo Knights',
    'Ninjago The Movie',
    'Hero Factory',
]

# Keywords that could be in sets, but aren't broad themes
SET_BRANDS = [
    'Star-Lord',
    'Gamora',
    'Kylo Ren',
    'Sith Trooper',
    'Mandalorian',
    'Wonder Woman',
    'Han Solo',
    'Chewbacca',
    'Groot',
    'Luke Skywalker',
    'Yoda',
    'Darth Vader',
    'Hermione',
    'Voldemort',
    'Donald Duck',
    'Manchester United',
    'FC Barcelona',
    'Spice Girls',
    'Chip & Dale',
    'Buzz Lightyear',
    'Wile E. Coyote',
    'Hogwarts',
    'Captain Phasma',
    'Iron Man',
    'Captain America',
    'Jack Sparrow',
    'Dr. Strange',
    'Supergirl',
    'Leia Organa',
    'Newt Scamander',
    'Marty McFly',
    'Doc Brown',
    'Mr. Incredible',
    'Frozone',
    'Thanos',
    'Spider-Man',
    'Batgirl',
    'Goofy',
    'Jake Sully',
    'Hagrid',
    'McLaren',
    'Porsche',
    'Ferrari',
    'Ford',
    'Chevrolet',
    'Land Rover',
    'BMW',
    'Volvo',
    'Lamborghini',
    'Ducati',
    'Bugatti',
    'Airbus',
    'John Deere',
    'Jeep',
    'Mercedes-Benz',
    'Batman',
    'Dom’s',
    'Boeing',
    # 'Mini',  # This is tricky
    'Liebherr',
    'CLAAS',
    'Unimog',
    'Finnjet'
    'Kelloggs',
    'McDuck',
    'Black Widow',
    'The Hulk',
    'The Flash',
    'The Joker',
    'Harry Potter',
    'Ron Weasley',
    'Albus Dumbledore',
    'Peter Venkman',
    'Mickey Mouse',
    'Minnie Mouse',
    'Boba Fett',
    'Homer Simpson',
    'Krusty the Clown',
    'Jack Skellington',
    'Aquaman',
    'Stormtrooper',
    'Ursula',
    'Daisy Duck',
    'Ahsoka Tano',
    'Demogorgon',
    'Elsa',
    'Olaf',
    'Wyldstyle',
    'Gru',
    'Rey',
    'Emmet',
    'Ninjago',
    'Belle Bottom',
    'Woody',
    'Lloyd',
    'Captain Armando Salazar',
    'Belle',
    'Creeper',
    'Finn',
    'Master Wu',
    'Robin',
    'Owen & Blue',
]
